CREATE SCHEMA Crawler;
USE Crawler;
CREATE TABLE  Urls (Id INT NOT NULL AUTO_INCREMENT, UrlHash CHAR(40) UNIQUE, Url VARCHAR(2048), Domain VARCHAR(253), Level TINYINT, Crawled BOOLEAN, Successful BOOLEAN, PRIMARY KEY(Id)) ENGINE = MYISAM;